# Generated by Django 4.2.5 on 2023-09-05 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Completada'), (2, 'Pendiente'), (3, 'cancelada')])),
                ('firma', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='completos')),
            ],
        ),
    ]
