# Generated by Django 4.2.5 on 2023-09-05 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Completada'), (3, 'cancelada')]),
        ),
    ]
