# Generated by Django 4.2.5 on 2023-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tarea_tecnico_alter_tarea_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='tarea',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='completos'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='completos'),
        ),
    ]
