# Generated by Django 4.2.5 on 2023-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_image_tarea_image_1_tarea_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='firma',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
