# Generated by Django 4.2.5 on 2023-09-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tarea_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='firma',
            field=models.TextField(blank=True),
        ),
    ]
