# Generated by Django 4.2.5 on 2023-09-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tarea_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='recibio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
