# Generated by Django 4.2.5 on 2023-09-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tarea_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='correo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tecnico'),
        ),
    ]
