# Generated by Django 4.2.5 on 2023-09-11 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tarea_correo_alter_tarea_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='pdfs/')),
                ('relacion_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tarea')),
            ],
        ),
    ]
