# Generated by Django 4.2.5 on 2023-09-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_pdfgenerado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfgenerado',
            name='relacion_datos',
        ),
    ]
