# Generated by Django 4.2.5 on 2023-09-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_pdfgenerado_relacion_datos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfgenerado',
            old_name='archivo_pdf',
            new_name='archivo',
        ),
    ]
