# Generated by Django 4.2.5 on 2023-09-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_pdfgenerado_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfgenerado',
            name='tarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.tarea'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pdfgenerado',
            unique_together={('tarea',)},
        ),
    ]
