# Generated by Django 4.2.5 on 2023-09-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_pdfgenerado_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
