# Generated by Django 4.2.5 on 2023-09-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_pdfgenerado_tarea_alter_pdfgenerado_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='correo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
