# Generated by Django 4.2.5 on 2023-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_tarea_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='notas',
            field=models.TextField(default=' '),
        ),
    ]
