# Generated by Django 4.2.5 on 2023-09-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_tarea_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estatus_pago',
            field=models.IntegerField(choices=[(1, 'no pagado'), (2, 'cobrado'), (3, 'cancelada')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='image_persona',
            field=models.ImageField(blank=True, null=True, upload_to='completos'),
        ),
    ]
