# Generated by Django 4.2.5 on 2023-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tarea_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='completos'),
        ),
    ]
