# Generated by Django 4.2.5 on 2023-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_tarea_estatus_pago_tarea_image_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estatus_pago',
            field=models.IntegerField(),
        ),
    ]
