# Generated by Django 4.2.5 on 2023-09-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_tarea_image_4'),
        ('tasks', '0022_historial_pagos'),
    ]

    operations = [
    ]
