# Generated by Django 4.2.5 on 2023-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_merge_0016_tarea_image_4_0022_historial_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estatus_Factura',
            field=models.IntegerField(choices=[(1, 'no facturado'), (2, 'facturado')], default=1),
        ),
        migrations.AddField(
            model_name='tarea',
            name='no_Factura',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='no_Factura_nota',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Completada'), (3, 'En Proceso'), (4, 'cancelada')], default=1),
        ),
    ]
