# Generated by Django 4.2.5 on 2023-09-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_tarea_estatus_factura_tarea_no_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='notas_tecnico',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='correo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
