# Generated by Django 4.2.5 on 2023-09-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_tarea_notas_tecnico_alter_tarea_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cliente',
            field=models.CharField(default='s', max_length=150),
            preserve_default=False,
        ),
    ]
